#mit:
#  forest-config:
#    log-enabled: false
#    log-response-content: true
#  code:
#    enable: true
#    datasource:
#      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      driver-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#    package-base: com.zrtg.demo
#    project-name: mittool-test
#


mit:

#  code:
#    datasource:
#      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: root
#    package-base: com.zrtg.demo
#    enable: true

#  weblog:
#    enable: true
#    request: true
#    response: true

